version: "3.8"

services:
    db:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root1234
            MYSQL_DATABASE: dev
            MYSQL_USER: root
            MYSQL_PASSWORD: root@1234
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"

volumes:
    db_data:
